"""users gender

Revision ID: f68be7c8d9c1
Revises: 695cd33cc256
Create Date: 2023-05-21 11:00:36.110930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68be7c8d9c1'
down_revision = '695cd33cc256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_gender'), ['gender'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_gender'))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
